# Generated by Django 5.0.6 on 2024-07-31 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('CollabName', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('Admin', models.CharField(max_length=200)),
                ('CreationTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollabMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MemberName', models.CharField(max_length=200)),
                ('Message', models.CharField(max_length=1000)),
                ('MessageTime', models.DateTimeField(auto_now_add=True)),
                ('CollabName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Collaboration.collaboration')),
            ],
        ),
        migrations.CreateModel(
            name='CollabMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CollabMembers', models.CharField(max_length=200)),
                ('JoinTime', models.DateTimeField(auto_now_add=True)),
                ('CollabName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Collaboration.collaboration')),
            ],
        ),
        migrations.CreateModel(
            name='CollabData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MemberName', models.CharField(max_length=200)),
                ('SharingTime', models.DateTimeField(auto_now_add=True)),
                ('DataType', models.CharField(max_length=10)),
                ('Link', models.FileField(blank=True, null=True, upload_to='uploads/collab/')),
                ('Data', models.CharField(blank=True, max_length=1000, null=True)),
                ('Comment', models.CharField(blank=True, max_length=200, null=True)),
                ('CollabName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Collaboration.collaboration')),
            ],
        ),
    ]
