# Generated by Django 5.0.6 on 2024-08-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collaboration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='CollabName',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
