# Generated by Django 5.0.6 on 2024-08-01 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Collaboration', '0002_collaboration_id_alter_collaboration_collabname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collabmembers',
            name='CollabName',
        ),
        migrations.RemoveField(
            model_name='collabmessages',
            name='CollabName',
        ),
        migrations.DeleteModel(
            name='CollabData',
        ),
        migrations.DeleteModel(
            name='CollabMembers',
        ),
        migrations.DeleteModel(
            name='CollabMessages',
        ),
        migrations.DeleteModel(
            name='Collaboration',
        ),
    ]
