# Generated by Django 5.0.6 on 2024-08-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collaboration', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collabdata',
            name='Link',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
