# Generated by Django 5.0.6 on 2024-08-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collaboration', '0005_alter_collabdata_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collabdata',
            name='Link',
            field=models.FileField(blank=True, null=True, upload_to='uploads/collab'),
        ),
    ]
