# Generated by Django 5.0.6 on 2024-05-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToolModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ToolName', models.CharField(max_length=50)),
                ('ToolDescription', models.CharField(max_length=500)),
                ('Image', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
