# Generated by Django 5.0.6 on 2024-07-31 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0002_toolmodel_urlpattern'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToolModel',
        ),
    ]
