# Generated by Django 5.0.6 on 2024-05-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clipboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='File',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='linkmodel',
            name='Link',
            field=models.TextField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='textmodel',
            name='Text',
            field=models.TextField(max_length=1000, unique=True),
        ),
    ]
