# Generated by Django 5.0.6 on 2024-06-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clipboard', '0003_filemodel_user_obj_linkmodel_user_obj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmodel',
            name='Link',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='textmodel',
            name='Text',
            field=models.TextField(max_length=1000),
        ),
    ]
