# Generated by Django 5.0.6 on 2024-07-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clipboard', '0004_alter_linkmodel_link_alter_textmodel_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='Filename',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
