# Generated by Django 5.0.6 on 2024-07-06 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clipboard', '0006_alter_filemodel_user_obj_alter_linkmodel_user_obj_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkmodel',
            old_name='user_obj',
            new_name='user',
        ),
    ]
