# Generated by Django 5.0.6 on 2024-07-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clipboard', '0007_rename_user_obj_linkmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmodel',
            name='Link',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='linkmodel',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
