# Generated by Django 5.0.6 on 2024-07-06 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clipboard', '0008_alter_linkmodel_link_alter_linkmodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textmodel',
            old_name='user_obj',
            new_name='user',
        ),
    ]
